name: Validate and merge PR

on:
  workflow_dispatch:
    types: [try-merge]

jobs:
  do_merge:
    name: try_merge_pr_1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
          cache: 'pip'
      - run: pip install pyyaml==6.0

      - name: Setup committer id
        run: |
          git config --global user.email "pytorchmergebot@users.noreply.github.com"
          git config --global user.name "PyTorch MergeBot"
      - name: Merge PR
        env:
          PR_NUM: 1
          FORCE: ${{ github.event.client_payload.force}}
          ON_GREEN: ${{ github.event.client_payload.on_green}}
          LAND_CHECKS: ${{ github.event.client_payload.land_checks }}
          COMMENT_ID: 1398991134
          REBASE: ${{ github.event.client_payload.rebase }}
        run: |
          if [ -n "${FORCE}"; then
            python3 .github/scripts/trymerge.py --force "${PR_NUM}"
          else
            python3 .github/scripts/trymerge.py "${PR_NUM}"
          fi
